### ISSUE TITLE
Thermal wathcdog started N times?

### ISSUE THREAD

**Issue by aolofsson** [parallella/parallella-utils#5]
cc @olajep 

Might be user error, was this the correct way to disable?
```
# parallella-thermald - Parallella Thermal Watchdog
#
# Disables Epiphany chip if system temperature gets to high/low.

description     "Parallella Thermal Watchdog"

start on runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 10 5
umask 022

env EPIPHANY_HOME=/opt/adapteva/esdk
# Uncomment below line to modify upper temperature limit
#env THERMALD_MAX_TEMP=70

console none

pre-start script
end script

script
    #. $EPIPHANY_HOME/setup.sh
    #/usr/sbin/parallella-thermald 2>&1 | logger -t parallella-thermald
end script
```

----
LOG FILE FROM BOOT

* Setting up X socket directories...                                    [ OK ]
 * Stopping System V initialisation compatibility                        [ OK ]
 * Starting System V runlevel compatibility                              [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Starting save kernel messages                                         [ OK ]
 * Starting OpenSSH server                                               [ OK ]
 * Starting regular background program processing daemon                 [ OK ]
 * Starting deferred execution scheduler                                 [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Stopping save kernel messages                                         [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Starting NTP server ntpd                                              [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Starting Parallella Thermal Watchdog                                  [ OK ]
 * Starting Parallella Thermal Watchdog                                  [fail]
 * Stopping Parallella Thermal Watchdog                                  [ OK ]

**Comment by olajep** [comment]
no correct way is
```
echo manual | sudo tee /etc/init/parallella-thermald.override
```

https://askubuntu.com/questions/19320/how-to-enable-or-disable-services

**Comment by olajep** [comment]
user error  ;)
(and irrelevant in Pubuntu 2016.3)
Right way to disable in Pubuntu 2016.3:
```
sudo systemctl mask "parallella-thermald@.service"
```
